### ISSUE TITLE
A suggestion about README.md And A strange phenomenon

### ISSUE THREAD

**Issue by Henry0132** [thu-ml/SRPO#2]
Hi!
I ran this project in Ubuntu20.04 successfully by using `TASK="halfcheetah-medium-v2"; seed=0; python3 -u train_behavior.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed}`   and   `TASK="halfcheetah-medium-v2"; seed=0; python3 -u train_critic.py --expid ${TASK}-baseline-seed${seed} --env $TASK --seed ${seed}`

Thus,I think your system is Ubuntu.

But when I ran these code in Windows10, some errors have happened.So I have a suggestion about README.md.

If someone want use Windows to run this project,he may use this code `$env:TASK="halfcheetah-medium-v2"; $env:seed=0; python -u train_behavior.py --expid $env:TASK-baseline-seed$env:seed --env $env:TASK --seed $env:seed` and `$env:TASK="halfcheetah-medium-v2"; $env:seed=0; python -u train_critic.py --expid $env:TASK-baseline-seed$env:seed --env $env:TASK --seed $env:seed`

Similarly,if he wants to train the policy,just rewrite the code as mentioned above.

Finally，I want to know,when I run this code successfully,the terminal show me that

![6a127f430c8abf65936f5302b38a029](https://github.com/thu-ml/SRPO/assets/132733568/7a66820f-934f-4fd4-be23-620de281d161)

and WandB has a figure

![ab4d1c45331e06ee6f6031646ae228a](https://github.com/thu-ml/SRPO/assets/132733568/196280cc-1a53-485d-a879-80b0b0ff5596)

The progress bar for training behavior has consistently remained at 0%, suggesting that the behavior is not being trained. Is this a normal occurrence?

**Comment by ChenDRAG** [comment]
Yeah, my system is Ubuntu. Thanks a lot for your suggestions.  I  will update the readme shortly after.   

You have run this code successfully. There is a small bug in the progress bar, which can be ignored. I've updated the code to fix this.

**Comment by Henry0132** [comment]
Thank you very much for your dedicated contribution to this project!
Looking forward to engaging in more in-depth discussions with you!
