### ISSUE TITLE
Question about policy output

### ISSUE THREAD

**Issue by fvgt** [thu-ml/SRPO#3]
Hi!

I was wondering the following, the Dirac policy only returns actions in the range of -1 and 1, since the activation function in the last layer is the tanh function. Thus, I think for environments that have an action space, that is outside of that range, your method might under perform, or am I missing something?

Maybe it would be convenient to scale the policy output by the action space of the environment.

**Comment by ChenDRAG** [comment]
Yes. The policy network needs to be redefined if your action space is not [-1,1].  One simple choice is to linearly scale and bias the output.  The D4RL tasks reported in the paper all have action spaces of [-1,1], though.

**Comment by fvgt** [comment]
Right, it is no big deal, thanks for clarifying it regardless!
